### ISSUE TITLE
Docker Hub needs Content-Type header on tag 'put'?

### ISSUE THREAD

**Issue by weberjm** [javajawa/remote-docker-tag#1]
While trying to use this action to update tags on a Docker Hub image, the action completes but no tags are added to the image. 

From the logs:
```
##[debug]Posting manifest to      https://registry.hub.docker.com/v2/xxxxxxxx/yyyyyy/manifests/1.0.0
##[debug]{"size":0,"timeout":0}
```
While trying from my API Editor (Insomnia), I received similar results, except when I included the Content-Type header with value matching the GET request (`application/vnd.docker.distribution.manifest.v2+json`). 

I believe this will be a simple update, and will create a PR. Have you seen similar behavior?

**Comment by weberjm** [comment]
The Content-Type header is not listed as required in [the documentation](https://docs.docker.com/registry/spec/api/#put-manifest), but it is included in all of the example calls.

The [Registry API overview](https://docs.docker.com/registry/spec/api/#pushing-an-image-manifest) does say 
> The content type should match the type of the manifest being uploaded

**Comment by weberjm** [comment]
It turns out the error which was being suppressed on the PUT was a 401, as my token was not being properly passed. I am still going to check the Content-Type issue.

Also, when the JSON is unmodified and passed directly back into the PUT query, the digest should stay the same. Currently that is not happening, so I will see if I can figure that out.

**Comment by javajawa** [comment]
Hello and thanks for the feedback!

I think there's three key improvements to capture here 
1. Explicitly setting a content type in the API calls for clarity and future compatibility
2. Improving the error handling: capturing 201 as a success, 401 as an auth error, etc.
3. Improving the logging when the action debug mode is enabled.

A lot of what you have put in #2 will be usable on the above points (and I'm going to have to add a contributors list 😸). Feel free to throw more PR work at any of the above; I don't think I'm going to be able to look at the the code until Friday afternoon euro time.

**Comment by javajawa** [comment]
I took a look at https://github.com/openintegrationhub/openintegrationhub/pull/1204 and I've realised I have never actually used the `auth` input of this project*. The main thing I have noted is that https://github.com/javajawa/remote-docker-tag/blob/mainline/tag.js#L71 return whatever the secret is with no prefix, unlike https://github.com/javajawa/remote-docker-tag/blob/mainline/tag.js#L92 which has the `Basic ` prefix.

Your issue may be fixable by adding the appropriate `<scheme>` to the front of the token provided to the action -- assuming it is not already present.


* My own uses have all been with Amazon ECR, using the provided ecr-login github action.

**Comment by weberjm** [comment]
Thanks for the feedback. I did recognize that the Bearer token scheme was not being added, and later added that to the workflow. 

You can always see the latest copy here: https://github.com/openintegrationhub/openintegrationhub/blob/master/.github/workflows/tagReleases.yml

However, with later testing on my fork, I still received errors of Invalid Manifest if I did not update the Content-Type in the PUT request. Based on my research with Insomnia (my API client, like Postman), when I used the "raw"  value of the response body to pipe back into the request body of the new tag manifest, then the tag would be added to the same digest as the previous tag. However, by using the JSON request value, a new digest would be created, having the same size and layers as the old digest. I'm not sure why that is, but I am going to try next if we can create a duplex stream to directly pipe the response manifest to the request manifest without any potential modification when passing through a "base JSON" format.

I closed my previous PR because I was using my fork mainline to test and debug my release action. If and when I get the remaining digest issue worked out, I will create a cleaned-up PR.

**Comment by weberjm** [comment]
So, instead of having to run my own duplex stream, passing the manifest as a Blob instead of JSON worked correctly for me to create a new tag on the same image. 

The cause is because the manifest file is also included in the contents of the image which are hashed to create the digest. The manifest as generated by Docker in a build is outputted with newlines, but in parsing the file and stringifying it, these are dropped and replaced with whatever whitespace is defined in the stringify() options. By simply passing the Blob representation of the manifest along, the original characters are preserved.

I will send a PR with these updates to you to review. It also has a little more logging, as you mentioned above.

**Comment by javajawa** [comment]
In retrospect, not just doing it as a blob makes a lot more sense.

I've merged the functional change, but squashed down as one commit, in #4 (and closed #3), and I will leave this issue for you to close if you are happy :)

Also, lets see if this works...
@all-contributors please add @javajawa for code, infra
@all-contributors please add @weberjm for bugs and code

**Comment by javajawa** [comment]
@all-contributors please add @weberjm for bugs and code

**Comment by weberjm** [comment]
Looks good to me, and thanks for the contributor mention.
